## 지역별 사고날짜 추출 코드

In [1]:
import pandas as pd

In [33]:
df_이천_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전//전처리_이천.xlsx').iloc[:,1:]
df_이천_기온 = pd.read_excel('project_data/지역별 기온 데이터//경기_이천_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_이천_전처리['사고날짜'] = df_이천_전처리['사고번호'].apply(func)

df_이천_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2018012300100059,2018년 1월 23일 07시,2,경기도 이천시 장호원읍,3,0,1,0,0,차대사람 - 횡단중,...,1,0,1,경기도 이천시청,031-644-2382,44258,4070000,경기도 이천시,0.904348,2018-01-23
1,2018012600100067,2018년 1월 26일 07시,5,경기도 이천시 부발읍,2,0,0,1,0,차대사람 - 횡단중,...,1,1,1,경기도 이천시청,031-644-2382,44258,4070000,경기도 이천시,0.976000,2018-01-26

---

In [34]:
df_파주_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전//전처리_파주.xlsx').iloc[:,1:]
df_파주_기온 = pd.read_excel('project_data/지역별 기온 데이터//경기_파주_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_파주_전처리['사고날짜'] = df_파주_전처리['사고번호'].apply(func)

df_파주_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2018010100100393,2018년 1월 1일 20시,1,경기도 파주시 금촌동,3,0,1,0,0,차대사람 - 횡단중,...,1,1,1,파주시청,031-940-5791,44306,4060000,경기도 파주시,0.788462,2018-01-01
1,2018040200100049,2018년 4월 2일 05시,1,경기도 파주시 문산읍,4,1,0,0,0,차대사람 - 횡단중,...,1,1,1,파주시청,031-940-5791,44306,4060000,경기도 파주시,0.845000,2018-04-02

---

In [35]:
df_남해_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전/전처리_남해.xlsx').iloc[:,1:]
df_남해_기온 = pd.read_excel('project_data/지역별 기온 데이터/경남_남해_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_남해_전처리['사고날짜'] = df_남해_전처리['사고번호'].apply(func)

df_남해_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2018011200100306,2018년 1월 12일 12시,5,경상남도 남해군 삼동면,3,0,1,1,0,차대사람 - 횡단중,...,1,0,0,경상남도 남해군,055-860-3454,44287,5430000,경상남도 남해군,0.75,2018-01-12
1,2018011500100349,2018년 1월 15일 14시,1,경상남도 남해군 남해읍,3,0,1,0,0,차대사람 - 횡단중,...,0,0,1,경상남도 남해군,055-860-3454,44287,5430000,경상남도 남해군,1.25,2018-01-15

---

In [39]:
df_양산_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전/전처리_양산.xlsx').iloc[:,1:]
df_양산_기온 = pd.read_excel('project_data/지역별 기온 데이터/경남_양산_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_양산_전처리['사고날짜'] = df_양산_전처리['사고번호'].apply(func)

df_양산_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2018010200100333,2018년 1월 2일 17시,2,경상남도 양산시 동면,3,0,1,0,0,차대사람 - 횡단중,...,1,1,0,양산시 교통과,055-392-2883,44326,5380000,경상남도 양산시,0.285714,2018-01-02
1,2018011200100049,2018년 1월 12일 02시,5,경상남도 양산시 물금읍,3,0,1,0,0,차대사람 - 횡단중,...,1,1,0,양산시 교통과,055-392-2883,44326,5380000,경상남도 양산시,0.909091,2018-01-12

---

In [40]:
df_영덕_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전//전처리_영덕.xlsx').iloc[:,1:]
df_영덕_기온 = pd.read_excel('project_data/지역별 기온 데이터//경북_영덕_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_영덕_전처리['사고날짜'] = df_영덕_전처리['사고번호'].apply(func)

df_영덕_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2018092300100356,2018년 9월 23일 18시,0,경상북도 영덕군 강구면,4,1,0,0,0,차대사람 - 횡단중,...,1,0,1,포항국토관리사무소,054-260-2534,44027,5180000,경상북도 영덕군,0.294118,2018-09-23
1,2019041700100054,2019년 4월 17일 04시,3,경상북도 영덕군 강구면,3,0,1,0,0,차대사람 - 횡단중,...,1,0,1,포항국토관리사무소,054-260-2534,44027,5180000,경상북도 영덕군,0.294118,2019-04-17

---

In [41]:
df_여수_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전//전처리_여수.xlsx').iloc[:,1:]
df_여수_기온 = pd.read_excel('project_data/지역별 기온 데이터//전남_여수_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_여수_전처리['사고날짜'] = df_여수_전처리['사고번호'].apply(func)

df_여수_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2018010800100615,2018년 1월 8일 23시,1,전라남도 여수시 신기동,3,0,1,0,0,차대사람 - 횡단중,...,1,1,1,전라남도 여수시청,061-659-5213,44105,4810000,전라남도 여수시,0.72,2018-01-08
1,2018011200100095,2018년 1월 12일 06시,5,전라남도 여수시 봉강동,3,0,1,0,0,차대사람 - 횡단중,...,1,1,1,전라남도 여수시청,061-659-5213,44105,4810000,전라남도 여수시,0.72,2018-01-12

---

In [42]:
df_함평_전처리 = pd.read_excel('project_data/시간, 기온 전처리 전//전처리_함평.xlsx').iloc[:,1:]
df_함평_기온 = pd.read_excel('project_data/지역별 기온 데이터//전남_함평_기온.xlsx')

def func(x):
    result = str(x)
    return result[:4] + '-' + result[4:6] + '-' + result[6:8]
    
df_함평_전처리['사고날짜'] = df_함평_전처리['사고번호'].apply(func)

df_함평_전처리.head(2)

,사고번호,사고일시,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,보도턱낮춤여부,점자블록유무,집중조명시설유무,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명,속도,사고날짜
0,2019031300100369,2019년 3월 13일 15시,3,전라남도 함평군 함평읍,4,1,0,0,0,차대사람 - 횡단중,...,1,0,0,함평군,061-320-1587,44077,4960000,전라남도 함평군,0.44,2019-03-13

In [46]:
# df_이천_전처리.to_excel('project_data/시간 전처리/시간_전처리_이천.xlsx')
# df_파주_전처리.to_excel('project_data/시간 전처리/시간_전처리_파주.xlsx')
# df_남해_전처리.to_excel('project_data/시간 전처리/시간_전처리_남해.xlsx')
# df_양산_전처리.to_excel('project_data/시간 전처리/시간_전처리_양산.xlsx')
# df_영덕_전처리.to_excel('project_data/시간 전처리/시간_전처리_영덕.xlsx')
# df_여수_전처리.to_excel('project_data/시간 전처리/시간_전처리_여수.xlsx')
# df_함평_전처리.to_excel('project_data/시간 전처리/시간_전처리_함평.xlsx')